export const offices = [
  "Office of the Dean",
  "Department Chairperson's Office",
  "Office of the Registrar",
  "Office of the Academic Affairs/Vice President for Academic Affairs (VPAA)",
  "Office of the Research and Development",
  "Office of the President",
  "Office of the Vice President for Administration/Finance",
  "Budget and Finance Office",
  "Human Resource Management Office (HRMO)",
  "Supply and Procurement Office",
  "Office of Student Affairs (OSA)",
  "Guidance and Counseling Office",
  "Scholarship and Financial Assistance Office",
  "Office of the Student Government",
  "Medical and Dental Clinic",
  "Campus Security and Safety Office",
  "ICT/Management Information Systems (MIS) Office",
  "Library and Learning Resource Center",
  "Quality Assurance (QA) Office",
];

export const positions = [
  "Instructor I",
  "Instructor II",
  "Instructor II",
  "Assistant Professor I",
  "Assistant Professor II",
  "Assistant Professor III",
  "Assistant Professor IV",
  "Associate Professor I",
  "Associate Professor II",
  "Associate Professor III",
  "Associate Professor IV",
  "Professor I",
  "Professor II",
  "Professor III",
  "Professor IV",
  "Professor V",
  "Professor VI",
];

export const branches = [
  "Tandag",
  "Lianga",
  "Tagbina",
  "San Miguel",
  "Cagwait",
  "Cantilan",
] as const;
